# -*- coding: utf-8 -*-
"""Static checks for QGIS 4 / Qt6 compatibility patterns.

This script intentionally scans plugin-owned Python files only. Vendored
dependencies and this checker are excluded because they may contain fallback
patterns by design.

Two kinds of check:

1. Line patterns (``CHECKS``) for known QGIS 3 -> 4 API breaks.
2. Unscoped Qt enum members that PyQt6 no longer exposes on the class, e.g.
   ``Qt.SizeVerCursor`` (PyQt6: ``Qt.CursorShape.SizeVerCursor``),
   ``Qt.Key_Escape``, ``Qt.ControlModifier``, ``QMessageBox.Yes``. The member
   list comes from ``qt6_unscoped_enums.json``, generated by introspecting
   ``qgis.PyQt`` inside a QGIS 4 Python (so QGIS's own compatibility patches,
   e.g. ``QVariant.Int``, are respected) - regenerate it with::

       <QGIS 4 python> tests/check_qgis_compat.py --regenerate-qt6-enums

   A use is accepted when it is guarded: inside an ``if``/conditional
   expression that tests ``hasattr``/``getattr`` on the same class or a
   Qt/QGIS version constant, inside a ``try`` that handles AttributeError,
   or as the default argument of ``getattr``. Mark a deliberate exception
   with a ``# qgis-compat: ignore`` comment on the line.

Runs on plain Python (no QGIS needed): ``python tests/check_qgis_compat.py``.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKIP_DIRS = {".venv", "venv", "lib", "__pycache__", "ref", ".git", ".agents", ".codex",
             "dist", "build"}
SKIP_FILES = {
    Path("qgis_compat.py"),
    Path("tests/check_qgis_compat.py"),
}
QT6_ENUMS_FILE = Path(__file__).resolve().with_name("qt6_unscoped_enums.json")
IGNORE_PRAGMA = "qgis-compat: ignore"

CHECKS = (
    ("QSvgWidget from QtSvg (use qgis_compat)", re.compile(r"QtSvg\s+import\s+.*\bQSvgWidget\b")),
    ("Qt exec_", re.compile(r"\.exec_\(")),
    ("QAction from QtWidgets", re.compile(r"QtWidgets\s+import\s+.*\bQAction\b")),
    ("unscoped QDialog result", re.compile(r"QDialog\.Accepted")),
    ("unscoped QSizePolicy", re.compile(r"QSizePolicy\.Expanding")),
    ("unscoped item-view enum", re.compile(r"QAbstractItemView\.(ExtendedSelection|SingleSelection|SelectRows|DoubleClicked|SelectedClicked|EditKeyPressed)")),
    ("unscoped header resize mode", re.compile(r"QHeaderView\.(Interactive|Stretch|Fixed|ResizeToContents|Custom)")),
    ("unscoped Qgis message level", re.compile(r"Qgis\.(Info|Warning|Critical|Success)")),
    ("unscoped geometry enum", re.compile(r"QgsWkbTypes\.(LineGeometry|PointGeometry|PolygonGeometry|NullGeometry)")),
    ("layer instance type enum", re.compile(
        r"QgsMapLayerProxyModel\."
        r"(VectorLayer|RasterLayer|PointLayer|LineLayer|PolygonLayer)\b")),
    ("QVariant field type", re.compile(r"QVariant\.(String|Double|Int|LongLong|Bool)")),
    ("processing number enum", re.compile(r"QgsProcessingParameterNumber\.(Double|Integer)")),
    ("processing field enum", re.compile(r"QgsProcessingParameterField\.(Numeric|Any)")),
    ("unscoped Qt window flag", re.compile(r"Qt\.(Window[A-Za-z]*Hint|FramelessWindowHint|WindowStaysOnTopHint)")),
)

REQUIRED_COMPAT_ALIASES = (
    "WINDOW_TYPE_WINDOW", "WINDOW_HINT_CUSTOMIZE", "WINDOW_HINT_TITLE",
    "WINDOW_HINT_MIN_MAX", "WINDOW_HINT_CLOSE",
    "WKB_POINT", "WKB_LINESTRING", "WKB_NO_GEOMETRY",
    "WKB_POINT_Z", "WKB_POINT_M",
    "HEADER_RESIZE_MODE_FIXED",
    "MAP_LAYER_FILTER_VECTOR", "MAP_LAYER_FILTER_POLYGON",
    "VECTOR_WRITER_OVERWRITE_LAYER", "VECTOR_WRITER_OVERWRITE_FILE",
    "VECTOR_WRITER_NO_ERROR",
    "DRAG_DROP_MODE_INTERNAL_MOVE", "DROP_ACTION_MOVE",
)

# Qt modules whose classes are introspected for the enum table.
QT_MODULES = ("QtCore", "QtGui", "QtWidgets", "QtPrintSupport", "QtSvg", "QtXml", "QtNetwork",
              "QtTest")
VERSION_GUARD_NAMES = {"QT_VERSION", "QT_VERSION_STR", "PYQT_VERSION", "PYQT_VERSION_STR",
                       "QGIS_VERSION_INT", "Qgis.QGIS_VERSION_INT", "QT6", "IS_QT6", "QT5", "IS_QT5"}


def iter_python_files() -> list[Path]:
    files: list[Path] = []
    for path in sorted(ROOT.rglob("*.py")):
        rel = path.relative_to(ROOT)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        if rel in SKIP_FILES:
            continue
        files.append(path)
    return files


# --------------------------------------------------------------------------
# Unscoped Qt enum members (AST based)
# --------------------------------------------------------------------------

class EnumTable:
    """{class: {member: scope}} for members PyQt6 only exposes scoped."""

    def __init__(self, data: dict):
        self.meta = data.get("_meta", {})
        self.bases = data.get("bases", {})
        self._by_class: dict[str, dict[str, str]] = {}
        for cls, scopes in data.get("classes", {}).items():
            members = self._by_class.setdefault(cls, {})
            for scope, names in scopes.items():
                for name in names.split():
                    members.setdefault(name, scope)

    @classmethod
    def load(cls, path: Path = QT6_ENUMS_FILE) -> "EnumTable":
        return cls(json.loads(path.read_text(encoding="utf-8")))

    def classes(self) -> set[str]:
        return set(self._by_class) | set(self.bases)

    def scope_of(self, cls: str, member: str):
        for owner in [cls] + list(self.bases.get(cls, [])):
            scope = self._by_class.get(owner, {}).get(member)
            if scope is not None:
                return owner, scope
        return None


def _dotted(node) -> str:
    parts = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
        return ".".join(reversed(parts))
    return ""


def _class_ref(node, classes) -> str:
    """Class name for ``Qt`` / ``QtCore.Qt`` / ``QtWidgets.QMessageBox`` refs."""
    dotted = _dotted(node)
    if not dotted:
        return ""
    head, _, last = dotted.rpartition(".")
    if last not in classes:
        return ""
    if head and head.rpartition(".")[2] not in QT_MODULES:
        return ""
    return last


def _mentions_guard(test, cls: str) -> bool:
    for node in ast.walk(test):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and \
                node.func.id in ("hasattr", "getattr") and node.args:
            if _dotted(node.args[0]).rpartition(".")[2] == cls:
                return True
        if isinstance(node, (ast.Name, ast.Attribute)) and _dotted(node) in VERSION_GUARD_NAMES:
            return True
    return False


def _handles_attribute_error(handler: ast.ExceptHandler) -> bool:
    if handler.type is None:
        return True
    names = handler.type.elts if isinstance(handler.type, ast.Tuple) else [handler.type]
    return any(_dotted(n) in ("AttributeError", "Exception", "BaseException") for n in names)


def _is_guarded(node, parents, cls: str) -> bool:
    child = node
    parent = parents.get(child)
    while parent is not None:
        if isinstance(parent, (ast.If, ast.IfExp, ast.While)) and child is not parent.test:
            if _mentions_guard(parent.test, cls):
                return True
        if isinstance(parent, ast.Try):
            if child in parent.body and any(_handles_attribute_error(h) for h in parent.handlers):
                return True  # try: Qt.X / except AttributeError: Qt.Scope.X
            if child in parent.handlers and _handles_attribute_error(child):
                return True  # try: Qt.Scope.X / except AttributeError: Qt.X  (Qt5 fallback)
        if isinstance(parent, ast.Call) and isinstance(parent.func, ast.Name) and \
                parent.func.id == "getattr" and len(parent.args) >= 3 and child is parent.args[2]:
            return True
        if isinstance(parent, ast.BoolOp):  # hasattr(Qt, "X") and Qt.X
            if any(v is not child and _mentions_guard(v, cls) for v in parent.values):
                return True
        if isinstance(parent, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Module)):
            if isinstance(parent, ast.Module):
                return False
        child, parent = parent, parents.get(parent)
    return False


def find_unscoped_enums(source: str, table: EnumTable, filename: str = "<string>"):
    """[(line, "Qt.SizeVerCursor", "Qt.CursorShape.SizeVerCursor")] for unguarded uses."""
    tree = ast.parse(source, filename=filename)
    lines = source.splitlines()
    classes = table.classes()
    parents = {}
    for parent in ast.walk(tree):
        for child in ast.iter_child_nodes(parent):
            parents[child] = parent
    found = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Attribute) or not isinstance(node.ctx, ast.Load):
            continue
        cls = _class_ref(node.value, classes)
        if not cls:
            continue
        hit = table.scope_of(cls, node.attr)
        if hit is None:
            continue
        line = lines[node.lineno - 1] if node.lineno - 1 < len(lines) else ""
        if IGNORE_PRAGMA in line or _is_guarded(node, parents, cls):
            continue
        owner, scope = hit
        found.append((node.lineno, f"{_dotted(node.value)}.{node.attr}",
                      f"{_dotted(node.value)}.{scope}.{node.attr}"))
    return found


# --------------------------------------------------------------------------
# Table generation (QGIS 4 Python only)
# --------------------------------------------------------------------------

def regenerate_enum_table(path: Path = QT6_ENUMS_FILE) -> int:
    import enum
    import importlib
    import inspect

    from qgis.core import Qgis
    from qgis.PyQt.QtCore import PYQT_VERSION_STR, QT_VERSION_STR

    if not QT_VERSION_STR.startswith("6"):
        print(f"Run this under a QGIS 4 / Qt6 Python (found Qt {QT_VERSION_STR}).")
        return 2
    classes: dict[str, dict[str, str]] = {}
    all_classes = {}
    for module_name in QT_MODULES:
        try:
            module = importlib.import_module(f"qgis.PyQt.{module_name}")
        except ImportError:
            continue
        for cls_name, cls in vars(module).items():
            if not inspect.isclass(cls) or not (cls_name == "Qt" or cls_name.startswith("Q")):
                continue
            all_classes[cls_name] = cls
            scopes = {}
            for scope_name, scope in vars(cls).items():
                if inspect.isclass(scope) and issubclass(scope, enum.Enum):
                    missing = sorted(m for m in scope.__members__ if not hasattr(cls, m))
                    if missing:
                        scopes[scope_name] = " ".join(missing)
            if scopes:
                classes[cls_name] = dict(sorted(scopes.items()))
    bases = {}
    for cls_name, cls in all_classes.items():
        chain = [b.__name__ for b in cls.__mro__[1:] if b.__name__ in classes]
        if chain:
            bases[cls_name] = chain
    meta = {
        "generated_by": "tests/check_qgis_compat.py --regenerate-qt6-enums",
        "qgis": Qgis.QGIS_VERSION, "qt": QT_VERSION_STR, "pyqt": PYQT_VERSION_STR,
        "modules": list(QT_MODULES),
        "meaning": "members of Qt enums that PyQt6 exposes only under their enum scope",
    }

    def block(mapping):  # one line per class keeps diffs readable
        rows = [f"  {json.dumps(k)}: {json.dumps(v, separators=(',', ':'))}"
                for k, v in sorted(mapping.items())]
        return "{\n" + ",\n".join(rows) + "\n }"

    text = ('{\n "_meta": ' + json.dumps(meta) + ',\n "classes": ' + block(classes)
            + ',\n "bases": ' + block(bases) + "\n}\n")
    json.loads(text)  # sanity
    path.write_text(text, encoding="utf-8")
    members = sum(len(n.split()) for s in classes.values() for n in s.values())
    print(f"Wrote {path.name}: {len(classes)} classes, {members} scoped-only members "
          f"(QGIS {Qgis.QGIS_VERSION}, Qt {QT_VERSION_STR}, PyQt {PYQT_VERSION_STR}).")
    return 0


# --------------------------------------------------------------------------

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--regenerate-qt6-enums", action="store_true",
                        help="rebuild qt6_unscoped_enums.json (run under a QGIS 4 Python)")
    args = parser.parse_args(argv)
    if args.regenerate_qt6_enums:
        return regenerate_enum_table()

    failures: list[str] = []
    compat_text = (ROOT / "qgis_compat.py").read_text(encoding="utf-8-sig")
    for alias in REQUIRED_COMPAT_ALIASES:
        if not re.search(rf"^\s*{alias}\s*=", compat_text, re.MULTILINE):
            failures.append(f"qgis_compat.py: missing compatibility alias: {alias}")

    table = EnumTable.load() if QT6_ENUMS_FILE.exists() else None
    if table is None:
        failures.append(f"{QT6_ENUMS_FILE.name} missing: regenerate with --regenerate-qt6-enums")
    for path in iter_python_files():
        rel = path.relative_to(ROOT)
        text = path.read_text(encoding="utf-8-sig")
        for line_number, line in enumerate(text.splitlines(), start=1):
            if IGNORE_PRAGMA in line:
                continue
            for label, pattern in CHECKS:
                if pattern.search(line):
                    failures.append(f"{rel}:{line_number}: {label}: {line.strip()}")
        if table is not None:
            try:
                uses = find_unscoped_enums(text, table, str(rel))
            except SyntaxError as exc:
                failures.append(f"{rel}:{exc.lineno}: cannot parse: {exc.msg}")
                continue
            for line_number, used, scoped in uses:
                failures.append(f"{rel}:{line_number}: unscoped Qt enum (missing in PyQt6): "
                                f"{used} -> use {scoped} (or a qgis_compat alias)")

    if failures:
        print("QGIS compatibility check failed:")
        for failure in failures:
            print(f"  {failure}")
        return 1

    print("QGIS compatibility check passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
